version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: obrio-db-docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #   container_name: obrio-docker
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 5432
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: 1111
  #   depends_on:
  #     - db
